### ISSUE TITLE
Cannot control the reference id of collection entry

### ISSUE THREAD

**Issue by tuan-nng** [GetStream/stream-python#125]
## Problem explanation

add an entry to collection with specified id, collection entry should be created with that id.

## Steps to reproduce

```python
stored_data = stream_client.collections.add(collection_name="name", data=data,
                                                      id="ABC")
stored_data
{'duration': '4.08ms', 'id': 'd1dab993-a5f2-4c2d-b8e8-b670204f95c2', 'collection': 'name',...}
```

I expect that `stored_data['id'] = 'ABC'`

gz#5609

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/5609'>Zendesk ticket #5609</a>:<br><br>Thanks for the report

**Comment by tuan-nng** [comment]
I just realized that I passed the id as an object, not an actual string "ABC". (example code is simplified). I tested again and it worked.
