### ISSUE TITLE
Verify request retry behaviour of requests

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/stream-python#13]

**Comment by tbarbugli** [comment]
few thoughts:

* timeouts should be quick for production environments
* timeouts should not be too aggressive on development
* we should not retry failed responses (eg. 4xx, 5xx)
* aggressive timeouts + retry might be a good fit for lot of production applications

**Comment by matthisk** [comment]
For fine grain control over retries we should use urllibr [Retry class](http://urllib3.readthedocs.org/en/latest/helpers.html?highlight=retries#module-urllib3.util.retry). When passing an instance of this class to ```max_retries``` on ```HTTPAdapter``` you can control retry behavior.

According to the docs this behavior only applies to failed connections and timeouts, but I guess if you supply an instance of the Retry class you can have more control:

**max_retries (int)** – The maximum number of retries each connection should attempt. Note, this applies only to failed connections and timeouts, never to requests where the server returns a response.
