### ISSUE TITLE
can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by SidAtNSIO** [GetStream/stream-python#132]
## Problem explanation
"can only concatenate str (not "bytes") to str" this error occurs when we are assigning a user to feed group

## Steps to reproduce

client.feed('user', str(some_id))

## Environment info

Operating System: Ubuntu 20.04
Python version: Python 3.8.10
Library version: 5.1.0

## Error traceback (if applicable)

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/path/to/stream_python-5.1.0-py3.8.egg/stream/client.py", line 118, in feed
    return Feed(self, feed_slug, user_id, token)
  File "/path/to/stream_python-5.1.0-py3.8.egg/stream/feed.py", line 29, in __init__
    self.signature = self.feed_together + " " + self.token
TypeError: can only concatenate str (not "bytes") to str
```

## Code snippet that causes the problem

```python
client.feed('user', str(some_id))
```

**Comment by ferhatelmas** [comment]
What is the version pyjwt in your project?

cc @peterdeme

**Comment by SidAtNSIO** [comment]
pyjwt = 1.7.1

**Comment by peterdeme** [comment]
So it seems like the bytes vs str behavior of PyJWT has changed [here](https://github.com/jpadilla/pyjwt/pull/513). If I see it correctly that's version `2.0`.

So @SidAtNSIO, you're not supposed to use anything less that that.

**Comment by ferhatelmas** [comment]
fixed in https://github.com/GetStream/stream-python/releases/tag/v5.1.1
