### ISSUE TITLE
Is it possible to use channel.get_replies async?

### ISSUE THREAD

**Issue by RayBB** [GetStream/stream-python#138]
## Problem explanation
I'd like to use `channel.get_replies(parent_id=message_id)` but async.

Is this possible?

Based on this file, which seems to have most async code, it doesn't look like it. But wanted to ask here to be sure. 
https://github.com/GetStream/stream-python/blob/b4515d337be88ff50ba1cbad8645b1fbc8862ce0/stream/client/async_client.py

Use case is pretty much just that we're getting some replies client side for caching purposes and async would be handy so we can easily fire off requests concurrently.

Thanks!

**Comment by ferhatelmas** [comment]
this is a chat endpoint, you can find here https://github.com/getstream/stream-chat-python

this is a feed sdk.
