### ISSUE TITLE
TO parameter is edited in place

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/stream-python#24]
if you add an activity

activity = dict(to=['a'])
feed.add_activity(activity)
activity.to no longer equals ['a']
it's edited in place....

**Comment by tschellenbach** [comment]
Seems broken for add_activity and add_activities
https://github.com/GetStream/stream-python/blob/master/stream/feed.py#L49

**Comment by matthisk** [comment]
fixed in #30
