### ISSUE TITLE
add support for activity_copy_limit to follow_many

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/stream-python#26]

**Comment by matthisk** [comment]
I don't understand the batch follow [api endpoint](http://getstream.io/docs_rest/#follow_many). How can we supply a list as data (with follow relations) and at the same time supply a dictionary property ``activity_copy_limit``.

**Comment by tbarbugli** [comment]
`activity_copy_limit` is sent as a query parameter to the endpoint
