### ISSUE TITLE
find out what's wrong with httpsig

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/stream-python#29]
very often setup install fails with this error:

```
running test
Searching for httpsig==1.1.2
Reading https://pypi.python.org/simple/httpsig/
No local packages or download links found for httpsig==1.1.2
error: Could not find suitable distribution for Requirement.parse('httpsig==1.1.2')
```

There is clearly something really broken in httpsig library

**Comment by matthisk** [comment]
Found issue, waiting for response @ [https://github.com/ahknight/httpsig/issues/5](https://github.com/ahknight/httpsig/issues/5)

**Comment by tbarbugli** [comment]
httpsig mantainer finally fixed this (only wheel were distributed)
