### ISSUE TITLE
feed.add_activities() fails when activities empty list

### ISSUE THREAD

**Issue by maryokhin** [GetStream/stream-python#42]
If `activity_list` is passed in [add_activities](https://github.com/GetStream/stream-python/blob/master/stream/feed.py#L75) as an empty list, then the client will make a request to the API and crash with an uncaught & obscure error message. Don't have the logs already, but it was complaining that necessary fields like `verb`, `actor` were missing.

**Comment by maryokhin** [comment]
Usually client libraries handle corner cases, so I didn't bother to check for empty list before calling the method :)

**Comment by tschellenbach** [comment]
Thank you for reporting this!

**Comment by tbarbugli** [comment]
this is going to be part of the next release
