### ISSUE TITLE
Allow for client use on app engine with request_toolbelt

### ISSUE THREAD

**Issue by jmylen** [GetStream/stream-python#43]
Hey team,

I just started playing around with this client and because of some issues with App Engine and the requests library it took me a while.

In order to get it working I used requests_toolbelt which uses an Adapter compatible with App Engine. 

A quick fix on your end to make it compatible would just be to update line 9 in client.py to

from requests.sessions import HTTPAdapter

as this is what's being patched by request_toolbelt as seen in the link below.

https://github.com/sigmavirus24/requests-toolbelt/blob/master/requests_toolbelt/adapters/appengine.py#L126

**Comment by JelteF** [comment]
I think it makes more sense to change the requests-toolbelt lib. So I made a pull request for it here:
https://github.com/sigmavirus24/requests-toolbelt/pull/165

**Comment by JelteF** [comment]
The patch has been merged so the issue should be fixed now. If other issues still occur please let me know.
