### ISSUE TITLE
install_requires inlcudes httpsig which requires PyCrypto which is dead

### ISSUE THREAD

**Issue by crimsdings** [GetStream/stream-python#64]
install_requires = [
    'pyjwt==1.3.0',
    'requests>=2.2.1',
    'six>=1.8.0',
    'httpsig==1.1.2'
]

->     'httpsig==1.1.2' 
https://pypi.python.org/pypi/httpsig
Requirements
    Python 2.7, 3.2, 3.3, 3.4
    PyCrypto

PyCrypto is officially dead see https://github.com/dlitz/pycrypto/issues/238 - and wont compile on python 3.6 windows systems.

consider moving away from an outdated httpsig 2015-Feb-11

**Comment by dwightgunning** [comment]
Thanks for the heads up! I will look into this shortly.
