### ISSUE TITLE
I need a bulk delete activity method.

### ISSUE THREAD

**Issue by japrogramer** [GetStream/stream-python#75]
Currently there is a create_activities methods for feeds but I don't see a remove_activities equivalent.

**Comment by dwightgunning** [comment]
Deleting activities in bulk isn't a supported operation. Depending on the scenario / use case there are typically preferable ways to achieve the desired functionality without explicitly deleting activities. 

It's best to [contact support](https://getstream.io/contact/) directly to discuss implementation specific use-cases.
