### ISSUE TITLE
Is there a bulk unfollow uperator?

### ISSUE THREAD

**Issue by japrogramer** [GetStream/stream-python#80]
Whenever i delete a user in my staging enviorment because of the way my model delete cascade a singal request is made per deleted model of Follow type.

This causes a rate limit error to be hit

However if there was a bulk unfollow method I could than in my user model pre delete signal 
get all the follow models that are related and bulk delete them from the stream api.

Im not to concern for the signal being firred when i delete the Follows because it would be a bulk delete operation that doesn't fire a signal.

**Comment by dwightgunning** [comment]
Batch unfollow is on our roadmap. While we're considering implementing the feature we can't commit to a timeline / release date at this stage.
