### ISSUE TITLE
Support JWT > 1.3.0

### ISSUE THREAD

**Issue by dedayoa** [GetStream/stream-python#82]
## Problem explanation

Having stream-python installed with say djangorestframework-jwt raises this notice
![image](https://user-images.githubusercontent.com/2971690/42580672-f8a43636-8522-11e8-8679-ad2b27f427a7.png)
PyJWT is at 1.6.4, but stream-python is still tied to 1.3.0

## Steps to reproduce
Install stream-python, then install latest pyjwt (or any package that depends on the latest pyjwt)

## Environment info

Windows 10
Python version: 3.6.2
Library version: stream-python 2.9.0 (installing stream_django)

Issue has been opened for this in the past
https://github.com/GetStream/stream-python/pull/20

**Comment by dedayoa** [comment]
Is there any reason why stream-python is tied to jwt 1.3.0?

**Comment by tbarbugli** [comment]
@dedayoa this is fixed on latest release (1.9.2)
