### ISSUE TITLE
Proposal: simplify implementation by dropping intermediary variable

### ISSUE THREAD

**Issue by ferhatelmas** [GetStream/stream-python#95]
## Problem explanation

Nothing specifically wrong but could be improved, IMHO.

```python
        response = self.client.post(
            resource,
            service_name="personalization",
            params=params,
            signature=self.token,
            data=data,
        )
        return response
```

Generally, previous idiom is followed but `response` could be returned directly without losing any significant information but it might improve readability by making implementation shorter since it's repeated many times.

Suggestion is as following:

```diff
-        response = self.client.post(
+        return self.client.post(
             resource,
             service_name="personalization",
             params=params,
             signature=self.token,
             data=data,
         )
-        return response
```

## Steps to reproduce

None, above description is self contained.

## Environment info

N/A

## Error traceback (if applicable)

N/A

## Code snippet that causes the problem

N/A

**Comment by ferhatelmas** [comment]
so what is the result? No need to bother?

**Comment by tbarbugli** [comment]
Yup
