### ISSUE TITLE
Stop using strict versions in requires

### ISSUE THREAD

**Issue by leibowitz** [GetStream/stream-python#98]
## Problem explanation

It is currently not possible to use both [`stream-python`](https://github.com/GetStream/stream-python/blob/b4ca4f1f985725e6da2e847e958a5507397c7e7b/setup.py#L19) and [`stream-chat-python`](https://github.com/GetStream/stream-chat-python/blob/fabf3e14b4c13a33367c9b0142577a4d9ca4c02d/setup.py#L9) within the same python environment, due to `pycryptodomex` requires version dependency.

It would be pretty easy to relax the dependency with >= (instead of strict equal), in both projects

## Steps to reproduce

`pip install stream-python stream-chat-python`

## Environment info

OSX 10.14.5
Python version: 3.7.4
Library version: 3.1.0

## Error traceback (if applicable)

```
ERROR: stream-chat 1.0.1 has requirement pycryptodomex==3.8.1, but you'll have pycryptodomex 3.4.7 which is incompatible.
```

## Code snippet that causes the problem

n/a

**Comment by tbarbugli** [comment]
thank you for letting us know, this is clearly a major issue and we are going to fix this asap

**Comment by leibowitz** [comment]
related https://github.com/GetStream/stream-python/pull/94

**Comment by tbarbugli** [comment]
fixed and released
